import { Inter } from "next/font/google";
import "./globals.css";
import { navData } from "@/lib/navData";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav class="bg-blue-500 p-4">
          <div class="container mx-auto flex items-center justify-between">
            <div class="text-white font-bold text-xl">Logo</div>
            <div class="space-x-4">
              {navData.data.map((e, index) => (
                <a href={e.link} class="text-white" key={index}>
                  {e.titile}
                </a>
              ))}
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
